# Generated by Django 4.2.23 on 2025-09-13 06:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('events', models.JSONField(default=list)),
                ('secret', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'webhook_endpoints',
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('student.updated', 'Student updated'), ('consent.changed', 'Consent changed')], max_length=64)),
                ('payload', models.JSONField()),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('attempts', models.IntegerField(default=0)),
                ('last_status_code', models.IntegerField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('next_retry_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='integrations.webhookendpoint')),
            ],
            options={
                'db_table': 'webhook_deliveries',
                'indexes': [models.Index(fields=['status', 'next_retry_at'], name='webhook_del_status_741062_idx')],
            },
        ),
    ]
